# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# https://zenn.dev/yiskw713/articles/3c3b4022f3e3f22d276d
default_stages: [commit]
default_install_hook_types: [pre-commit,pre-push,commit-msg,post-checkout,post-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-added-large-files
      - id: check-json
        exclude: ".devcontainer/"
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: pretty-format-json
        exclude: ".devcontainer/"
        args: [--autofix]
      - id: no-commit-to-branch
        args: [--branch, master, --branch, develop, --branch, stage, --branch, production]
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black --check .
        language: python
        types: [file, python]
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort --check .
        language: python
        types: [file, python]
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: bash -c 'export MYPYPATH="$(basename -- "$(pwd)")" && mypy --show-error-context . '
        language: python
        types: [file, python]
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: pflake8 --show-source .
        language: python
        types: [file, python]
  - repo: local
    hooks:
      - id: bandit
        name: bandit
        entry: poetry run task bandit
        language: python
        types: [file, python]
  - repo: local
    hooks:
      - id: poetry-export
        name: poetry-export
        entry: poetry export -f requirements.txt -o requirements.txt --without-hashes
        language: python
        types: [file, python]
  - repo: local
    hooks:
      - id: pre-push
        name: pre-push
        entry: bash -c "if ! echo `git symbolic-ref HEAD | sed s%^refs/heads/%%` | grep -E 'feature/CCDS[0-9]{3,4}' > /dev/null ; then echo 'このブランチはプッシュしないでください。' && exit 1; fi"
        language: system
        always_run: true
        stages: [push]