# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# https://zenn.dev/yiskw713/articles/3c3b4022f3e3f22d276d
default_stages: [commit]
default_install_hook_types: [pre-commit,pre-push,commit-msg,post-checkout,post-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-added-large-files
      - id: check-json
        exclude: ".devcontainer/"
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: pretty-format-json
        exclude: ".devcontainer/"
        args: [--autofix]
      - id: no-commit-to-branch
        args: [--branch, master, --branch, develop, --branch, stage, --branch, production]
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black --check .
        language: python
        types: [file, python]
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort --check .
        language: python
        types: [file, python]
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: poetry run mypy .
        language: python
        types: [file, python]
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: poetry run flake8 --show-source --exclude=.venv/* --max-line-length=109 --ignore=E402 --max-complexity=10 --max-expression-complexity=10 --max-cognitive-complexity=10 .
        additional_dependencies: [flake8-eradicate, pep8-naming, flake8-expression-complexity, flake8-cognitive-complexity]
        language: python
        types: [file, python]
  - repo: local
    hooks:
      - id: bandit
        name: bandit
        entry: poetry run bandit -c pyproject.toml -r .
        language: python
        types: [file, python]