version: '3.9'

services:
  app:
    container_name: dev_container
    build:
      target: dev
      context: ./
      dockerfile: ./docker/app/Dockerfile
    command: sh -c 'sleep infinity'
    volumes:
      - .:/poetry_practice
    ports:
      - 8081:8081
