version: '3.9'
services:
  app:
    container_name: dev_container
    build:
      target: dev
      context: ./
      dockerfile: ./docker/Dockerfile
      args:
        - ENVIRONMENT=DEV
    volumes:
      - .:/poetry_practice
