version: '3.9'
services:
  app:
    container_name: prod_container
    build:
      target: prod
      context: ./
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/poetry_practice
