version: '3.9'
services:
  app:
    working_dir: /poetry_practice
    environment:
      TZ: Asia/Tokyo
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
      PYTHONUTF8: 1
      PIP_NO_CACHE_DIR: 'off'
      PIP_DISABLE_PIP_VERSION_CHECK: 'on'
    tty: true
    stdin_open: true

  db:
    image: mysql:8.0
    environment:
      TZ: 'Asia/Tokyo'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'users'
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33306:3306
    depends_on:
      - app

volumes:
  mysql-volume:
    driver: local
